language: c
services:
  - docker
before_install:
    - docker pull anlun/compiler-workout-ci
    - docker run -d -it --name compiler-workout-ci -e "TRAVIS_COMMIT=$TRAVIS_COMMIT" -e "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG" anlun/compiler-workout-ci
script:
     docker exec -it compiler-workout-ci sh test.sh
